name: "LCDproc Client"
description: "A LCDproc client for Home Assistant"
version: "0.1.11"
slug: "lcdproc_client"
url: https://github.com/rohbags/ha-lcdproc-client
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
homeassistant_api: true # for /api (sensors)
# Role-based access to Supervisor API. Available: default, homeassistant, backup, manager or admin
hassio_role: homeassistant
hassio_api: true
options:
  lcdproc_host: null
  lcdproc_port: 13666
  show_default: true
  show_cpu: true
  show_mem: true
  show_net: false
  show_disk: false
  show_sensors: false
  list_sensors: ""
  debug: false
schema:
  lcdproc_host: str
  lcdproc_port: port
  show_default: bool
  show_cpu: bool
  show_mem: bool
  show_net: bool
  show_disk: bool
  show_sensors: bool
  list_sensors: str?
  debug: bool

